// <auto-generated />
namespace Desafio.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UsuarioDataCriacaoNaoComputada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsuarioDataCriacaoNaoComputada));
        
        string IMigrationMetadata.Id
        {
            get { return "201604220556418_Usuario-DataCriacao-NaoComputada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
